### ISSUE TITLE
Does this support OpenBalena v4.1.x?

### ISSUE THREAD

**Issue by alekbless** [dcaputo-harmoni/open-balena-admin#42]
I just tried setting up open-balena-admin to test this nice looking, and helpful software. 

When accessing :8080 after all containers started, connected to PostgreSQL DB, i'am returned with: Not Found

Blank page with Not Found. 

Using latest OpenBalena. Any suggestions on where to start debugging?

**Comment by brydenver2** [comment]
I am hoping the dev replies, but I have found that the issue with the NotFound has to do with the REACT_APP_BANNER_IMAGE env variable.  I added an image but I believe the resolution is wrong as I just get a blank screen.  I think, the banner image that is in the container was some how corrupted or missing for a default.

**Comment by brydenver2** [comment]
Actually after digging into the UI docker image I believe it is looking for the API version tag but it does not exist for API v30. I'm looking into the coding for the versions to see if any changes need to be made or if we can just you the last listed version.

**Comment by dcaputo-harmoni** [comment]
@giuseppe443 @alekbless apologies for the delay in jumping in here - there have been a lot of updates to the open-balena-admin app since those docker scripts were built. The primary method of deploying it is in kubernetes via helm, and I've been keeping those up to date. If you look at the commit logs of the various open-balena-admin components (ui, postgres, remote) you should see the environment variables / other configuration items that have been added, and I would welcome any PR's to keep those docker scripts updated. Otherwise I'm sure I'll get around to this at some point, it's just not a focus at the moment.

**Comment by andreatondelli** [comment]
After fixing the database connection (above and [here](https://github.com/dcaputo-harmoni/open-balena-admin/issues/41)) and addressing the "Not Found" message (environment variable `REACT_APP_BANNER_IMAGE`), I now see a blank page.

Based on the previous messages, it looks like the dashboard is visible, although with reduced functionality. Is that correct, or did I misunderstand something? 

Just to be able to use the tool while waiting for a permanent solution.

In case it can be useful, my console message under the blank page
```
index.js:76 Uncaught TypeError: Cannot read properties of undefined (reading 'resources')
    at Object.resource (index.js:76:1)
    at eval (deviceType.js:5:1)
    at 5130 (main.e70a06462544a7c8714d.js:1:194)
    at u (runtime.2a73d18749b01e5d3491.js:1:153)
    at main.e70a06462544a7c8714d.js:1:760535
    at u.O (runtime.2a73d18749b01e5d3491.js:1:476)
    at main.e70a06462544a7c8714d.js:1:760552
    at n (runtime.2a73d18749b01e5d3491.js:1:2000)
    at main.e70a06462544a7c8714d.js:1:71
```
```
74: const resource = (resource, version) => {
75:   const targetVer = semver.maxSatisfying(Object.keys(versions), `<=${version.split('v')[1]}`);
76:   return versions[targetVer].resources[resource];   // <=============[error here]===============
77: };
```

Thanks!

**Comment by andreatondelli** [comment]
Hi @giuseppe443, thanks to quick reply.

You're right, I have `34.3.17` instead of **`v34.3.17`.**

With the correct notation (including `v`), the login page is displayed.

Now I can see the dashboard pages, but they have no content, and I always get a "fetch failed" toast message. Is this correct, or is there another issue I can fix on my own to at least view the status of the devices or services while waiting for a proper version of Open-Balena-Admin?  

Thank you so much!

**Comment by andreatondelli** [comment]
Hi @giuseppe443 
i have already changed the hostname of the db and also the network according to my comments on [other issue](https://github.com/dcaputo-harmoni/open-balena-admin/issues/41).

I realized later that it was the browser that couldn't resolve that address, so I had to add it to the client's hosts file.

Now I'm getting another error: a toast with message `role "anon" does not exist`.

Looking inside the container (`docker logs -f open-balena-db-1`), the more detailed error is 
```
2025-02-05 13:33:42.711 UTC [238918] ERROR:  role "anon" does not exist
2025-02-05 13:33:42.711 UTC [238918] STATEMENT:  select set_config('search_path', $1, true), set_config('role', $2, true), set_config('request.jwt.claims', $3, true), set_config('request.method', $4, true), set_config('request.path', $5, true), set_config('request.headers', $6, true), set_config('request.cookies', $7, true)
```
Thank you

**Comment by andreatondelli** [comment]
> Cant say i have seen this problem before. Did you do a fresh install of openbalena v4.* or an update from an older version?
> 

I installed openbalena first time last month with version 4.1.311


> > [@giuseppe443](https://github.com/giuseppe443) thanks for the notes, I am planning to upgrade openbalena to latest in the next few weeks, will post any changes to these repos necessary to support it after that process is complete.
> 
> I have found the problem and the solution. I havent created a PR because i am not sure if this is a problem of my own creation or not. But the problem i had was that in open-balena-ui DeviceConnect.js was trying to set the username by getting it from [session.object.username](https://github.com/dcaputo-harmoni/open-balena-ui/blob/491aea9d90786bfe56723a6f36c786e3e910902b/src/ui/DeviceConnect.js#L110), but username wasnt available in the object.
> 
> i did a quick and dirty modification and it works like this
> 
> ```
> const userId = session.object.id;
> 
>       dataProvider.getList('user', {
>         pagination: { page: 1, perPage: 1000 },
>         sort: { field: 'id', order: 'ASC' },
>         filter: { id: userId },
>       })
>       .then((user) => {
>         const username = user.data[0].username;
>         setUsername(username);
>         return username;
>       });
> ```

I don't find [your pull request](https://github.com/dcaputo-harmoni/open-balena-ui/pulls) so i don't understand how to fix (quick and dirty :-D ) this piece of code 


```
  const upsertUserPublicKey = (publicKeySsh) => {
    const keyTitle = 'open-balena-remote';
    return dataProvider
      .getList('user', {
        pagination: { page: 1, perPage: 1000 },
        sort: { field: 'id', order: 'ASC' },
        filter: { username: username },
      })
      .then((user) => {
        return dataProvider
          .getList('user-has-public key', {
            pagination: { page: 1, perPage: 1000 },
            sort: { field: 'id', order: 'ASC' },
            filter: { user: user.data[0].id, title: keyTitle },
          })
          .then((remoteKey) => {
            if (remoteKey.data.length > 0) {
              return dataProvider.update('user-has-public key', {
                id: remoteKey.data[0].id,
                data: { 'user': user.data[0].id, 'title': keyTitle, 'public key': publicKeySsh },
              });
            } else {
              return dataProvider.create('user-has-public key', {
                data: { 'user': user.data[0].id, 'title': keyTitle, 'public key': publicKeySsh },
              });
            }
          });
      });
  };
```
I try this without success

```
const userId = session.object.id;
  const upsertUserPublicKey = (publicKeySsh) => {
    const keyTitle = 'open-balena-remote';
    return dataProvider
      .getList('user', {
        pagination: { page: 1, perPage: 1000 },
        sort: { field: 'id', order: 'ASC' },
        filter: { id: userId },
      })
      .then((user) => {
        const username = user.data[0].username;
        setUsername(username);
        return username;
      });
  };
```

Thanks.

**Comment by andreatondelli** [comment]
Hi @giuseppe443   

I don't think I quite understand what change I should try. Could you be more specific by telling me exactly where I need to make the modification and what I need to change? Maybe you could post the original piece of code and the modified one, just like I did.  

Thanks!
Andrea

**Comment by brydenver2** [comment]
Here is my Docker Compose if you want to update the container
```
`services:
  ui:
    extends:
      file: ./common.yml
      service: component
    image: harmonidcaputo/open-balena-ui:${OPENBALENA_UI_VERSION_TAG}
    depends_on:
      - postgrest
      - remote
    environment:
      - PORT=8080
      - REACT_APP_BANNER_IMAGE=./banner_illustration.svg
      - OPEN_BALENA_JWT_SECRET=${OPENBALENA_JWT_SECRET}
      - OPEN_BALENA_S3_URL=https://s3.${OPENBALENA_HOST_NAME}.com
      - OPEN_BALENA_S3_ACCESS_KEY=${OPENBALENA_S3_ACCESS_KEY}
      - OPEN_BALENA_S3_SECRET_KEY=${OPENBALENA_S3_SECRET_KEY}
      - OPEN_BALENA_S3_REGISTRY_BUCKET=registry-data
      - REACT_APP_OPEN_BALENA_UI_URL=https://admin.${OPENBALENA_HOST_NAME}
      - REACT_APP_OPEN_BALENA_POSTGREST_URL=https://postgrest.${OPENBALENA_HOST_NAME}
      - REACT_APP_OPEN_BALENA_REMOTE_URL=https://remote.${OPENBALENA_HOST_NAME}
      - REACT_APP_OPEN_BALENA_API_URL=https://api.${OPENBALENA_HOST_NAME}
      - REACT_APP_OPEN_BALENA_API_VERSION=${OPENBALENA_API_VERSION_TAG}
    ports:
      - "8080:8080"
    networks:
      open-balena_default:
        aliases:
          - admin.${OPENBALENA_HOST_NAME}

  remote:
    extends:
      file: ./common.yml
      service: component
    image: harmonidcaputo/open-balena-remote:${OPENBALENA_REMOTE_VERSION_TAG}
    environment:
      BALENARC_BALENA_URL: ${OPENBALENA_HOST_NAME}
      HOST_MODE: ${OPENBALENA_ADMIN_HOST_MODE}
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
      - "10003:10003"
      - "10004:10004"
      - "10005:10005"
      - "10006:10006"
      - "10007:10007"
      - "10008:10008"
      - "10009:10009"
    networks:
      open-balena_default:
          aliases:
             - remote.${OPENBALENA_HOST_NAME}

  postgrest:
    extends:
      file: ./common.yml
      service: component
    image: harmonidcaputo/open-balena-postgrest:${OPENBALENA_POSTGREST_VERSION_TAG}
    environment:
      PGRST_DB_URI: postgres://${OPENBALENA_DB_USERNAME}:${OPENBALENA_DB_PASSWORD}@open-balena-db-1:${OPENBALENA_DB_PORT}/resin
      PGRST_JWT_SECRET: ${OPENBALENA_JWT_SECRET}
    ports:
      - "8000:8000"
    networks:
      open-balena_default:
        aliases:
          - postgrest.${OPENBALENA_HOST_NAME}

networks:
  open-balena_default:
    external: true`
```

But I am running into the same issue as @andreatondelli as the Balena DB is showing:
```
`2025-06-09 22:37:26.158 UTC [51902] ERROR:  role "anon" does not exist

2025-06-09 22:37:26.158 UTC [51902] STATEMENT:  select set_config('search_path', $1, true), set_config('role', $2, true), set_config('request.jwt.claims', $3, true), set_config('request.method', $4, true), set_config('request.path', $5, true), set_config('request.headers', $6, true), set_config('request.cookies', $7, true)`
```

@giuseppe443 @dcaputo-harmoni  can you point me in the direction to correct this?
